### ISSUE TITLE
Seekbar not working

### ISSUE THREAD

**Issue by dishankEbizz** [Ahmedbadereldin/Video-Trimmer-Android#5]
Hello, Hope you are doing well.
When changing seekbar from thumb or moving to specific position video is always playing from the beginning, not from the seekbar's position. And duration also not updating according seekbar so can you please check and guide for it?

**Comment by Ahmedbadereldin** [comment]
@dishankEbizz 
I will check it. soon

**Comment by Ahmedbadereldin** [comment]
https://user-images.githubusercontent.com/22775683/206991427-88c3908e-ed0d-406c-a854-91d3ea0d01a8.mp4

the library works fine! 
can you send me video for the issues

**Comment by dishankEbizz** [comment]
I mean the purple seekbar. When we are updating that seekbar the video is not updating progress. It's not updating video duration as well. Please check below attached video

https://user-images.githubusercontent.com/69805613/207021733-6ff71557-03a8-4b6e-82f0-1ee6b5a792dd.mp4

**Comment by Ahmedbadereldin** [comment]
Solved

**Comment by dishankEbizz** [comment]
Thank you for resolving this.

**Comment by Ahmedbadereldin** [comment]
@dishankEbizz 
I am glad that I solved your problem.
Thank you
